/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Part 2: relative frequency of each population within each sample.
         */
        get: operations["get_summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filters
         * @description Distinct filter values, so the dashboard's dropdowns follow the data.
         */
        get: operations["get_filters_api_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Compare
         * @description Part 3: population frequencies in responders vs non-responders.
         *
         *     The assignment's cohort (melanoma, miraclib, PBMC) is the default rather
         *     than a hardcoded constant, so the same comparison can be run against any
         *     other indication or treatment without a code change.
         */
        get: operations["get_compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cohort
         * @description Part 4: baseline samples for one treatment arm, broken down by project,
         *     response and sex.
         *
         *     Counts are per subject for response and sex, because those are properties
         *     of a person rather than of a specimen. Project counts are per sample, as
         *     the question asks how many samples each project contributed.
         */
        get: operations["get_cohort_api_cohort_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryCount
         * @description A labelled count. Used for the per-project, per-response and per-sex
         *     breakdowns so the client can render them all with one component.
         */
        CategoryCount: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * CohortFilters
         * @description The filters that produced a result set, echoed back so the client can
         *     label charts without re-deriving what it asked for.
         */
        CohortFilters: {
            /** Condition */
            condition?: string | null;
            /** Treatment */
            treatment?: string | null;
            /** Sample Type */
            sample_type?: ("PBMC" | "WB") | null;
            /** Time From Treatment Start */
            time_from_treatment_start?: number | null;
            /** Sex */
            sex?: string | null;
            /** Proj Id */
            proj_id?: string | null;
        };
        /**
         * CrossTabRow
         * @description One row of a response x grouping cross-tabulation.
         */
        CrossTabRow: {
            /** Label */
            label: string;
            /** Responders */
            responders: number;
            /** Non Responders */
            non_responders: number;
            /** Not Recorded */
            not_recorded: number;
            /** Total */
            total: number;
        };
        /** CohortResponse */
        CohortResponse: {
            filters: components["schemas"]["CohortFilters"];
            /** Sample Ids */
            sample_ids: string[];
            /** N Samples */
            n_samples: number;
            /** N Subjects */
            n_subjects: number;
            /** Samples By Project */
            samples_by_project: components["schemas"]["CategoryCount"][];
            /** Subjects By Response */
            subjects_by_response: components["schemas"]["CategoryCount"][];
            /** Subjects By Sex */
            subjects_by_sex: components["schemas"]["CategoryCount"][];
            /** Response By Sex */
            response_by_sex: components["schemas"]["CrossTabRow"][];
            /** Response By Project */
            response_by_project: components["schemas"]["CrossTabRow"][];
        };
        /** CompareResponse */
        CompareResponse: {
            filters: components["schemas"]["CohortFilters"];
            /** N Samples */
            n_samples: number;
            /** N Subjects */
            n_subjects: number;
            /**
             * Test
             * @description Name of the statistical test applied
             */
            test: string;
            /**
             * Correction
             * @description Multiple-comparison correction method
             */
            correction: string;
            /** Alpha */
            alpha: number;
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "baseline" | "day7" | "day14";
            /**
             * Aggregation Note
             * @description Plain-language statement of how repeated measures per subject were handled, so a reader of the chart knows what each point represents.
             */
            aggregation_note: string;
            /** Points */
            points: components["schemas"]["FrequencyPoint"][];
            /** Tests */
            tests: components["schemas"]["PopulationTest"][];
        };
        /**
         * FilterOptions
         * @description Distinct values available for each filter, read from the database so the
         *     UI never offers a combination the data cannot describe.
         */
        FilterOptions: {
            /** Conditions */
            conditions: string[];
            /** Treatments */
            treatments: string[];
            /** Sample Types */
            sample_types: string[];
            /** Timepoints */
            timepoints: number[];
            /** Projects */
            projects: string[];
        };
        /**
         * FrequencyPoint
         * @description A single observation feeding the boxplots. Carries subject so the client
         *     can show that samples are repeated measures rather than independent.
         */
        FrequencyPoint: {
            /** Sample */
            sample: string;
            /** Subject */
            subject: string;
            /** Population */
            population: string;
            /** Percentage */
            percentage: number;
            /**
             * Response
             * @enum {string}
             */
            response: "yes" | "no";
            /** Time From Treatment Start */
            time_from_treatment_start: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PopulationTest
         * @description Result of one test, for one population, between responders and non-responders.
         */
        PopulationTest: {
            /** Population */
            population: string;
            /** N Responders */
            n_responders: number;
            /** N Non Responders */
            n_non_responders: number;
            /** Median Responders */
            median_responders: number;
            /** Median Non Responders */
            median_non_responders: number;
            /**
             * Median Difference
             * @description responders minus non-responders
             */
            median_difference: number;
            /**
             * Statistic
             * @description Mann-Whitney U statistic
             */
            statistic: number;
            /** P Value */
            p_value: number;
            /**
             * P Value Adjusted
             * @description Corrected across all populations tested
             */
            p_value_adjusted: number;
            /**
             * Significant
             * @description p_value_adjusted < alpha
             */
            significant: boolean;
            /**
             * Effect Size
             * @description Rank-biserial correlation, -1 to 1. Near zero means the groups overlap almost entirely, regardless of the p-value.
             */
            effect_size: number;
            /**
             * P Value Welch
             * @description Welch's t-test p-value, reported as a sensitivity check. Agreement with the rank-based test is evidence the conclusion does not depend on which test was chosen.
             */
            p_value_welch: number;
            /**
             * Shapiro P Responders
             * @description Shapiro-Wilk p-value for the responder group. p < 0.05 means normality is rejected for that group.
             */
            shapiro_p_responders: number;
            /**
             * Shapiro P Non Responders
             * @description Shapiro-Wilk p-value for the non-responder group. p < 0.05 means normality is rejected for that group.
             */
            shapiro_p_non_responders: number;
            /**
             * Normality Rejected
             * @description True if Shapiro-Wilk rejects normality (p < 0.05) in either group. When true, MWU is the appropriate test over a t-test.
             */
            normality_rejected: boolean;
            /**
             * P Value Welch
             * @description Welch t-test p-value. Only computed when normality_rejected is False. Null when normality is rejected.
             */
            p_value_welch: number | null;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Rows */
            rows: components["schemas"]["SummaryRow"][];
            /** N Samples */
            n_samples: number;
            /** Populations */
            populations: string[];
        };
        /**
         * SummaryRow
         * @description One population from one sample. Column names match the assignment spec.
         */
        SummaryRow: {
            /** Sample */
            sample: string;
            /**
             * Total Count
             * @description Sum across all populations in this sample
             */
            total_count: number;
            /** Population */
            population: string;
            /** Count */
            count: number;
            /**
             * Percentage
             * @description count / total_count * 100
             */
            percentage: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_summary_api_summary_get: {
        parameters: {
            query?: {
                /** @description Restrict to a single sample id */
                sample?: string | null;
                /** @description Page size; omit to return every row */
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_api_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
        };
    };
    get_compare_api_compare_get: {
        parameters: {
            query?: {
                condition?: string;
                treatment?: string;
                sample_type?: "PBMC" | "WB";
                /** @description Which timepoint to use (baseline=day 0, day7, day14) */
                aggregation?: "baseline" | "day7" | "day14";
                /** @description Filter to M or F subjects only */
                sex?: string | null;
                /** @description Filter to a single project */
                proj_id?: string | null;
                alpha?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cohort_api_cohort_get: {
        parameters: {
            query?: {
                condition?: string;
                treatment?: string;
                sample_type?: "PBMC" | "WB";
                time_from_treatment_start?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
