/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Part 2: relative frequency of each population within each sample.
         */
        get: operations["get_summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Rows */
            rows: components["schemas"]["SummaryRow"][];
            /** N Samples */
            n_samples: number;
            /** Populations */
            populations: string[];
        };
        /**
         * SummaryRow
         * @description One population from one sample. Column names match the assignment spec.
         */
        SummaryRow: {
            /** Sample */
            sample: string;
            /**
             * Total Count
             * @description Sum across all populations in this sample
             */
            total_count: number;
            /** Population */
            population: string;
            /** Count */
            count: number;
            /**
             * Percentage
             * @description count / total_count * 100
             */
            percentage: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_summary_api_summary_get: {
        parameters: {
            query?: {
                /** @description Restrict to a single sample id */
                sample?: string | null;
                /** @description Page size; omit to return every row */
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
